blog/urls.py
from django.conf.urls import url

from blog import views

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^post/new/$', views.post_new, name='post_new'),
    url(r'^post/(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
    url(r'^drafts/$', views.post_draft_list, name='post_draft_list'),
    url(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
    url(r'^post/(?P<pk>\d+)/remove/$', views.post_remove, name='post_remove'),
    url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
    url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
]

board/urls.py
from django.conf.urls import url

from board import views

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    # url(r'^$', views.post_list, { 'ctg': '' }, name='post_list'),
    # url(r'^news/$', views.post_list, { 'ctg': 'news' }, name='news_post_list'),
    # url(r'^free/$', views.post_list, { 'ctg': 'free' }, name='free_post_list'),
    url(r'^post/new/$', views.post_new, name='post_new'),
    url(r'^post/(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
    # url(r'^drafts/$', views.post_draft_list, name='post_draft_list'),
    # url(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
    url(r'^post/(?P<pk>\d+)/remove/$', views.post_remove, name='post_remove'),
    # url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    # url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
    # url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static
from .views import TagListView
from . import views
from .views import home, UserRegister, UserRegisterDone

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^board/', include('board.urls', namespace='board')),
    url(r'^tag/(?P<tag>.*)/$', TagListView.as_view(), name='searchtag'),
    # url(r'^accounts/login/$', views.login, name='login'),
    # url(r'^accounts/logout/$', views.logout, name='logout', kwargs={'next_page': '/'}),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register/$', UserRegister.as_view(), name="register"),
    url(r'^accounts/register/done/$', UserRegisterDone.as_view(), name="register_done"),
]
urlpatterns += static('media', document_root=settings.MEDIA_ROOT)

board/models.py
from django.db import models
from taggit.managers import TaggableManager
import os
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=50)
    title = models.CharField(max_length=50)
    def __str__(self):
        return self.name



class Board(models.Model):
    title = models.CharField(max_length=200)
    text = models.TextField()
    author = models.ForeignKey('auth.User')
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(Category, null=True)


    def __str__(self):
        return self.title

# 파일 업로드
class File(models.Model):
    file = models.FileField(upload_to='files/%Y/%m/%d/', null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Board, null=True, on_delete=models.CASCADE)

    def filename(self):
        return os.path.basename(self.file.name)



    def delete(self, *args, **kwargs ):
        self.file.delete()
        super(File, self).delete(*args, **kwargs)

    def __str__(self):
        return self.file.name


# 이미지 업로드
class Image(models.Model):
    image = models.FileField(upload_to='images/%Y/%m/%d/', null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Board, null=True, on_delete=models.CASCADE)

    def filename(self):
        return os.path.basename(self.image.name)

    def delete(self, *args, **kwargs):
        self.image.delete()
        super(File, self).delete(*args, **kwargs)

    def __str__(self):
        return self.image.name

board/forms.py
from django import forms
from board.models import Board, File, Image

class BoardForm(forms.ModelForm):

    class Meta:
        model = Board
        fields = ('title', 'text', 'category')

class FileForm(forms.ModelForm):

    class Meta:
        model = File
        fields = ('file',)

class ImageForm(forms.ModelForm):

    class Meta:
        model = Image
        fields = ('image',)

board/views.py
from django.shortcuts import render
from board.models import Board, Category
from django.shortcuts import redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from board.models import File, Image

from board.forms import BoardForm, FileForm, ImageForm
# Create your views here.
def post_list(request):
    category = request.GET.get("category")
    if category != None:

        boards = Board.objects.filter(category__name = category)

    else:
        boards = Board.objects.all()

    category = Category.objects.all()
    return render(request, 'board/post_list.html', {'boards': boards, 'categolies': category})





# 캐릭터필드를 이용했을 때
# @login_required
# def post_list(request, ctg):
#     ctgr = Category.objects.all()
#     if ctg == 'news':
#         boards = Board.objects.filter(category = 2)
#     elif ctg == 'free':
#         boards = Board.objects.filter(category = 1)
#     else:
#         boards = Board.objects.all()
#
#     return render(request, 'board/post_list.html', {'boards': boards, 'ctgr': ctgr})



def post_detail(request, pk):

    board = get_object_or_404(Board, pk=pk)
    files = board.file_set.all()
    images = board.image_set.all()


    return render(request, 'board/post_detail.html', {'board': board, 'files': files, 'images': images})

@login_required
def post_new(request):

    if request.method == 'POST':
        form = BoardForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()

            upfls = request.FILES.getlist('file')
            for upfl in upfls:
                file = File()
                file.file = upfl
                file.post = post
                file.save()

            upimgs = request.FILES.getlist('image')
            for upimg in upimgs:
                img = Image()
                img.image = upimg
                img.post = post
                img.save()



            return redirect('board:post_detail', pk=post.pk)
    else:
        form = BoardForm()
        file = FileForm()
        image = ImageForm()

    return render(request, 'board/post_edit.html', {'form': form,'file': file, 'image': image})


def post_edit(request, pk):

    post = get_object_or_404(Board, pk=pk)
    if request.method == 'POST':
        form = BoardForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('board:post_detail', pk=post.pk)
    else:
        form = BoardForm(instance=post)

    return render(request, 'board/post_edit.html', {'form': form})

def post_remove(request, pk):
    board = get_object_or_404(Board, pk=pk)
    board.delete()
    return redirect('board:post_list')

board/templates/board/base.html
{% extends 'base.html' %}

{% block board %}
<head>
    <meta charset="UTF-8">
    <title>게시판</title>
</head>
    <div>
        <div>
            <h1><a href="{% url 'board:post_list' %}">게시판</a></h1>
            <a href="{% url 'board:post_list' %}">목록보기</a>

            {% for category in categolies %}
            <a href="{% url 'board:post_list' %}?category={{ category }}">{{ category.title }}</a>
            {% endfor %}


            <a href="{% url 'board:post_new' %}">새글쓰기</a>

        </div>
    </div>
 <div class="wrap">
     <div>

   <!--{{ boards }}-->

   {% block sub_content %}
   {% endblock %}

     </div>
</div>


{% endblock %}

board/templates/board/post_detail.html
{% extends 'board/base.html' %}
{% load static %}
{% block sub_content %}
<a href="{% url 'board:post_edit' board.pk %}">수정하기</a>
<a href="{% url 'board:post_remove' board.pk %}">삭제하기</a>
<a href=""></a>
<div>
    <p>타이틀 : {{ board.title }}</p><br>
    <p>유저 : {{ board.author }}</p><br>
    <p>내용 : {{ board.text }}</p><br>
    <p>카테고리 : {{ board.category }}</p><br>
</div>
<p>{% for image in images %}
    <img src="{% get_media_prefix %}{{ image }}" alt="{{ image.filename }}">
        {% endfor %} </p>
<p>{% for file in files %}
    <a href="{% get_media_prefix %}{{ file }}">{{ file.filename }}</a>
{% endfor %}</p>
<p>{% for music in musics %}
    <a href="{% get_media_prefix %}{{ music }}">{{ music }}</a>
{% endfor %}</p>



{% endblock %}

board/templates/board/post_edit.html
{% extends 'board/base.html' %}

{% block sub_content %}
<div>
	<h1>새 글쓰기</h1>
	
	<form action="" method="POST" enctype="multipart/form-data">
	    {% csrf_token %}
	    {{ form.as_p }}
		<p>첨부할 파일을 선택해 주세요.</p>
		{{ file.as_p }}
		<p>첨부할 이미지를 선택해 주세요.</p>
		{{ image.as_p }}
		<br>
	    <button type="submit">쓰기</button>

	</form>
</div>
{% endblock %}

board/templates/board/post_list.html
{% extends 'board/base.html' %}
{% block sub_content %}

        {% for board in boards %}

            <a href="{% url 'board:post_detail' pk=board.pk %}">
                <p>타이틀 : {{ board.title }}</p><hr>
                <p>유저 : {{ board.author }}</p><hr>
                <p>날짜 : {{ board.created_date }}</p><hr><br><br><br>
            </a>
        {% endfor %}
{% endblock %}
<!--{{ boards }}-->