blog/urls.py
from django.conf.urls import url

from blog import views

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^post/new/$', views.post_new, name='post_new'),
    url(r'^post/(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
    url(r'^drafts/$', views.post_draft_list, name='post_draft_list'),
    url(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
    url(r'^post/(?P<pk>\d+)/remove/$', views.post_remove, name='post_remove'),
    url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
    url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static
from .views import TagListView
from . import views
from .views import home, UserRegister, UserRegisterDone

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^board/', include('board.urls', namespace='board')),
    url(r'^tag/(?P<tag>.*)/$', TagListView.as_view(), name='searchtag'),
    # url(r'^accounts/login/$', views.login, name='login'),
    # url(r'^accounts/logout/$', views.logout, name='logout', kwargs={'next_page': '/'}),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register/$', UserRegister.as_view(), name="register"),
    url(r'^accounts/register/done/$', UserRegisterDone.as_view(), name="register_done"),
]
urlpatterns += static('media', document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from taggit.managers import TaggableManager
# Create your models here.

class Post(models.Model):
    DJANGO = 'DJ'
    PYTHON = 'PY'
    GIT = 'GIT'
    HTTML = 'HTML'
    PHOTOSHOP = 'PS'
    PLACE_TYPE_CHOICES = (
        (DJANGO, 'DJANGO'),
        (PYTHON, 'PYTHON'),
        (GIT, 'GIT'),
        (HTTML, 'HTML'),
        (PHOTOSHOP, 'PHOTOSHOP'),
    )
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    category = models.CharField(max_length=20, choices=PLACE_TYPE_CHOICES, null=True, blank=True)
    tags = TaggableManager()

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    def approved_comments(self):
        return self.comments.filter(approved_comment=True)

class Comment(models.Model):
    post = models.ForeignKey('blog.Post', related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True

        self.save()

    def __str__(self):
        return self.text

blog/forms.py
from django import forms

from blog.models import Post, Comment
# class Postform(forms.Form):
#     title = forms.CharField(max_length=200)
#     text = forms.Textarea()

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text', 'tags', 'category')


class CommnetForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('author', 'text',)

blog/views.py
from django.shortcuts import render
from django.shortcuts import redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from blog.models import Post, Comment
from django.utils import timezone
from blog.forms import PostForm, CommnetForm
from taggit.models import Tag
# Create your views here.

def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    tag = Tag.objects.all()
    return render(request, 'blog/post_list.html', {'posts': posts, 'tags':tag})

@login_required
def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            form.save_m2m()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = PostForm()

    return render(request, 'blog/post_edit.html', {'form': form})

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)

    return render(request, 'blog/post_detail.html', {'post': post})

@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            form.save_m2m()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)

    return render(request, 'blog/post_edit.html', {'form': form})

@login_required
def post_draft_list(request):
    posts = Post.objects.filter(published_date__isnull=True).order_by('created_date')
    return render(request, 'blog/post_draft_list.html', {'posts': posts})

@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('blog:post_detail', pk=pk)

def post_remove(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect('blog:post_list')

def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = CommnetForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = CommnetForm()
    return render(request, 'blog/add_comment_to_post.html', {'form': form})

@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('blog:post_detail', pk=comment.post.pk)
@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.delete()
    return redirect('blog:post_detail', pk=comment.post.pk)

blog/templates/blog/add_comment_to_post.html
{% extends 'blog/base.html' %}
{% block content %}
    {% if user.is_authenticated %}
        <h1>댓글쓰기</h1>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">쓰기</button>
            </form>
    {% endif %}
{% endblock %}

blog/templates/blog/base.html
{% extends 'base.html' %}
{% block blog %}
<head>
    <meta charset="UTF-8">
    <title>블로그</title>
</head>
<body>
    <div>
        <div>
            <h1><a href="{% url 'blog:post_list' %}">블로그</a></h1>
            <a href="{% url 'blog:post_list' %}">목록보기</a></h3>
            <a href="{% url 'blog:post_new' %}">새글쓰기</a></h4>
            <a href="{% url 'blog:post_draft_list' %}" >초안목록</a></h4>
        </div>
    </div>
 <div class="wrap clearfix">
{% block content %}
{% endblock %}
 </div>

</div>
</body>

{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% block content %}
<div>
        {% if user.is_authenticated %}
        <div>
         <a href="{% url 'blog:post_edit' pk=post.pk %} ">수정하기</a>
            <a href="{% url 'blog:post_remove' pk=post.pk %}">삭제하기</a>
            <a href="{% url 'blog:post_publish' pk=post.pk %}">배포하기</a>
        </div>
        {% endif %}
    <div>
        <hr>
            <h1 class="h1-title">타이틀: {{ post.title }}</h1>
        <hr>
            <p>{{ post.text|linebreaksbr }}</p>
        <hr>
            <p>{{ post.published_date }}</p>
            {% for post in post.tags.all %}
            <p>태그: {{ post }}</p>
            {% endfor %}
        <hr>
    </div>
{% if user.is_authenticated %}
        <a href="{% url 'blog:add_comment_to_post' pk=post.pk %}">댓글달기</a>
{% endif %}

{% if user.is_authenticated %}
    {% for comment in post.comments.all %}
        {% if user.is_authenticated or comment.approved_comment %}
            <div>
                <div>
                    {{ comment.created_date}}
                        {% if not comment.approved_comment %}
                        <a href="{% url 'blog:comment_remove' pk=comment.pk %}">삭제</a>
                        <a href="{% url 'blog:comment_approve' pk=comment.pk %}">승인</a>
                    {% endif %}
                </div>
                <strong>{{ comment.author }}</strong>
                <p>{{ comment.text|linebreaksbr }}</p>
            </div>
        {% endif %}
    {% empty %}
        <p>댓글이 없습니다.</p>
    {% endfor %}
{% endif %}
</div>
{% endblock %}

blog/templates/blog/post_draft_list.html
{% extends 'blog/base.html' %}
{% block content %}
    {% for post in posts %}
        <div class="draft-div">
        	<hr>
            <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">타이틀: {{ post.title }}</a></h1>

            <hr>
            <p>{{ post.text|truncatechars:200 }}</p>

            <p>create: {{ post.created_date|date:'y-m-d' }}</p>
            <hr>
        </div>
    {% endfor %}


{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}
{% block content %}
<div class="edit-div">
	<h1>새 글쓰기</h1>
	
	<form action="" method="POST">
	    {% csrf_token %}

	    {{ form.as_p }}
		<br>
	    <button type="submit">저장</button>

	</form>
</div>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% block content %}
    {{ block.super }}
    <!--{% for tag in tags %}-->
    <!--<p>태그: {{ tag }}</p>-->
    <!--{% endfor %}-->
    {% for post in posts %}
      <div>
        <section>
        <hr>
        <a href="{% url 'blog:post_detail' pk=post.pk %}">제목: {{ post.title }}</a>
        <hr>
          <p>내용: {{ post.text|linebreaksbr }}</p>
          <p>배포일: {{ post.published_date }}</p>
          <p>댓글: {{ post.approved_comments.count }}</p><hr>
          {% if user.is_authenticated %}
            <a href="{% url 'blog:post_remove' pk=post.pk %}">[삭제]</a>
          {% endif %}
<hr>
        </section>
      </div>
    {% endfor %}


{% endblock %}