blog/urls.py
from django.conf.urls import url

from blog import views

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^post/new/$', views.post_new, name='post_new'),
    url(r'^post/(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
    url(r'^drafts/$', views.post_draft_list, name='post_draft_list'),
    url(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
    url(r'^post/(?P<pk>\d+)/remove/$', views.post_remove, name='post_remove'),
    url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
    url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static
from .views import TagListView
from . import views
from .views import home, UserRegister, UserRegisterDone

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^board/', include('board.urls', namespace='board')),
    url(r'^tag/(?P<tag>.*)/$', TagListView.as_view(), name='searchtag'),
    # url(r'^accounts/login/$', views.login, name='login'),
    # url(r'^accounts/logout/$', views.logout, name='logout', kwargs={'next_page': '/'}),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register/$', UserRegister.as_view(), name="register"),
    url(r'^accounts/register/done/$', UserRegisterDone.as_view(), name="register_done"),
]
urlpatterns += static('media', document_root=settings.MEDIA_ROOT)

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>홈</title>
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
</head>
<body>
<div class="wrap">
    <header>
        <div>
            <h1><a href="/">홈</a></h1>
        </div>
    </header>
<div>
    {% if user.is_authenticated %}
        <div class="wrap">
            <p>안녕하세요. '{{ user.username }}'님</p>
            <a href="{% url 'logout' %}">로그아웃</a>
            <a href="{% url 'password_change' %}">비밀번호 변경</a>
            <a href="{% url 'admin:index' %}">관리자</a>
        </div>
    {% else %}
        <div >
            <a href="{% url 'login' %}">로그인</a>
            <a href="{% url 'register' %}">회원가입</a>
        </div>
    </div>
    {% endif %}
    <nav class="base-nav">
        <ul>
            <li><a href="{% url 'blog:post_list' %}">블로그</a></li>
            <li><a href="{% url 'board:post_list' %}">게시판</a></li>
        </ul>
    </nav>
    <h2>{% block title %}
        {% endblock %}
    </h2>
    {% block home %}
    {% endblock %}
    {% block blog %}
    {% endblock %}
    {% block board %}
    {% endblock %}
    {% block register %}
    {% endblock %}

</div>

templates/home.html
{% extends 'base.html' %}

{% block home %}

<div>
    <h1><a href="{% url 'blog:post_list' %}">블로그</a></h1>
    <ol>
        {% for post in posts %}
        <li><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a>
        </li>
        {% endfor %}
    </ol>

</div>
<div>
    <h1><a href="{% url 'board:post_list' %}">게시판 최신글</a></h1>
    <ol>
        {% for board in boards %}
        <li><a href="{% url 'board:post_detail' pk=board.pk %}">{{ board.title }} | {{ board.created_date }}</a></li>

        {% endfor %}
    </ol>
</div>
{% endblock %}

templates/searchtag.html
{% extends 'base.html' %}
{% block title %}태그검색{% endblock %}
{% block content %}

{% endblock %}